import os
import yaml
import logging
import argparse
import matplotlib
import matplotlib.pyplot as plt
from datetime import datetime
from pathlib import Path

# Force matplotlib to use non-interactive backend (Crucial for HPC/Ares)
matplotlib.use('Agg')

# Import our custom wrapper
from models.date_detector import DateDetector

# 1. Default fallback logger
logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

def setup_logging(log_path: str):
    """Configures logging to save to the specified file and output to console."""
    log_dir = os.path.dirname(log_path)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
        
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s',
        handlers=[
            logging.FileHandler(log_path),
            logging.StreamHandler()
        ],
        force=True 
    )
    logger.info(f"Logging successfully configured. Saving logs to: {log_path}")

def load_config(config_path: str) -> dict:
    """Loads the YAML configuration file."""
    if not os.path.exists(config_path):
        logger.error(f"Configuration file does not exist: {config_path}")
        raise FileNotFoundError(f"Missing file: {config_path}")
    with open(config_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

# Global dictionary to track metrics across epochs
metrics_history = {
    'epoch': [],
    'mAP50': [],
    'mAP50_95': []
}

def on_fit_epoch_end(trainer):
    """
    Callback function executed at the end of each training epoch.
    Extracts metrics, logs them, and generates an updated progress plot.
    """
    epoch = trainer.epoch + 1
    total_epochs = trainer.epochs
    metrics = trainer.metrics
    
    # Extract YOLOv8 standard validation metrics
    map50 = metrics.get('metrics/mAP50(B)', 0.0)
    map50_95 = metrics.get('metrics/mAP50-95(B)', 0.0)

    # Log to our custom logfile
    logger.info(f"Epoch [{epoch}/{total_epochs}] Completed | mAP@50: {map50:.4f} | mAP@50-95: {map50_95:.4f}")

    # Append to history
    metrics_history['epoch'].append(epoch)
    metrics_history['mAP50'].append(map50)
    metrics_history['mAP50_95'].append(map50_95)

    # Generate and save the plot
    try:
        plt.figure(figsize=(10, 6))
        plt.plot(metrics_history['epoch'], metrics_history['mAP50'], label='mAP@50', marker='o', color='blue')
        plt.plot(metrics_history['epoch'], metrics_history['mAP50_95'], label='mAP@50-95', marker='x', color='red')
        
        plt.title('Training Metrics Progress')
        plt.xlabel('Epoch')
        plt.ylabel('Score')
        plt.ylim(0, 1.0)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.legend(loc='lower right')
        
        # Save to the specific run directory generated by Ultralytics
        plot_path = Path(trainer.save_dir) / 'custom_training_progress.png'
        plt.savefig(plot_path, bbox_inches='tight')
        plt.close()
    except Exception as e:
        logger.error(f"Failed to generate training plot: {e}")

def main(config_path: str):
    config = load_config(config_path)
    
    # Setup custom logging
    log_path = config.get('logging_path', 'logs/train_detector.log')
    setup_logging(log_path)

    logger.info("=== Starting Detector Pipeline ===")
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    project_dir = Path("outputs/detector")
    run_name = f"run_{timestamp}"
    run_dir = project_dir / run_name
    
    run_dir.mkdir(parents=True, exist_ok=True)
    config_backup_path = run_dir / "detector_config.yaml"
    with open(config_backup_path, 'w', encoding='utf-8') as f:
        yaml.dump(config, f, sort_keys=False)
    logger.info(f"Configuration saved to {config_backup_path}")

    weights = config.get("model", {}).get("weights", "yolov8n.pt")
    detector = DateDetector(weights_path=weights)

    # Attach our custom callback to the YOLO model
    detector.model.add_callback("on_fit_epoch_end", on_fit_epoch_end)

    data_cfg = config.get("data", {})
    train_cfg = config.get("training", {})
    
    dataset_yaml = data_cfg.get("dataset_yaml", "data/processed/dataset.yaml")
    dataset_yaml_abs = os.path.abspath(dataset_yaml)
    if not os.path.exists(dataset_yaml_abs):
        logger.error(f"Dataset YAML not found at: {dataset_yaml_abs}")
        raise FileNotFoundError("Dataset YAML missing. Run preprocessor first.")

    logger.info("Initiating YOLO training engine...")
    detector.train(
        data=dataset_yaml_abs,
        epochs=train_cfg.get("epochs", 50),
        batch=train_cfg.get("batch_size", 16),
        imgsz=train_cfg.get("img_size", 640),
        optimizer=train_cfg.get("optimizer", "auto"),
        lr0=train_cfg.get("learning_rate", 0.001),
        patience=train_cfg.get("patience", 10),
        device=train_cfg.get("device", ""),
        workers=train_cfg.get("workers", 8),
        project=str(project_dir),
        name=run_name,
        exist_ok=True
    )

    logger.info("=== Training Completed ===")
    logger.info(f"Best weights and metrics are saved in: {run_dir}/weights/best.pt")
    logger.info(f"Custom progress plot is saved at: {run_dir}/custom_training_progress.png")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train the Expiry Date Bounding Box Detector.")
    parser.add_argument("--config", type=str, default="config/detector_config.yaml", help="Path to YAML config.")
    args = parser.parse_args()
    
    main(args.config)